### PR TITLE
Jaas666/add biome husky

### PR DESCRIPTION
**Pull request by jaas666**
This PR fixes issue #9 

First time setting up Biome and I kind of like it. Thanks for the suggestion.

This also sets husky with a pre-commit hook that will run the biome checks before accepting a commit.

biome configuration can be customized via the biome.json file.

Here's a link to [Biome's documetnation](https://biomejs.dev/guides/getting-started/)

I'm no expert so take this PR with a grain of salt.

### CODE REVIEW

**Comment by Aebel-Shajan** [comment]
Thank you for the pr :D, I appreciate it 🙏. 

I just tried running the biome commands on my local machine and I get these errors for some reason:

```bash
C:\Users\aebel\blah\blah> npm run lint:fix

> wocket-weague@0.0.0 lint:fix
> biome check --apply-unsafe ./**/*.{js,ts}

internalError/fs  DEPRECATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ! The argument --apply-unsafe is deprecated, it will be removed in the next major release. Use --write --unsafe instead.


./**/*.{js,ts} internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × The filename, directory name, or volume label syntax is incorrect. (os error 123)

  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


Checked 0 files in 125µs. No fixes applied.
```

It's not letting me apply the formatter

**Comment by Aebel-Shajan** [comment]
> Thank you for the pr :D, I appreciate it 🙏.
> 
> I just tried running the biome commands on my local machine and I get these errors for some reason:
> 
> ```shell
> C:\Users\aebel\blah\blah> npm run lint:fix
> 
> > wocket-weague@0.0.0 lint:fix
> > biome check --apply-unsafe ./**/*.{js,ts}
> 
> internalError/fs  DEPRECATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
>   ! The argument --apply-unsafe is deprecated, it will be removed in the next major release. Use --write --unsafe instead.
> 
> 
> ./**/*.{js,ts} internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
>   × The filename, directory name, or volume label syntax is incorrect. (os error 123)
> 
>   ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
> 
> 
> Checked 0 files in 125µs. No fixes applied.
> ```
> 
> It's not letting me apply the formatter

I think the issue is caused by my shell

> Caution
> Glob patterns used on the command line are not interpreted by Biome. They are expanded by your shell. Some shells don’t > > support the recursive glob **.
from: 
https://biomejs.dev/guides/configure-biome/#ignore-files

**Comment by Aebel-Shajan** [comment]
Also when using the --staged flag here:
```
"lint:staged": "biome check --error-on-warnings --no-errors-on-unmatched --staged ./**/*.{js,ts}",
```
Biome gets applied to all staged files, not the staged .js and .ts files. Really weird they would do it like that.

**Comment by jaas666** [comment]
> Also when using the --staged flag here:
> 
> ```
> "lint:staged": "biome check --error-on-warnings --no-errors-on-unmatched --staged ./**/*.{js,ts}",
> ```
> 
> Biome gets applied to all staged files, not the staged .js and .ts files. Really weird they would do it like that.

Hmmm I think I missed using lint-staged which should let us specify that. Hmm 🤔

I can try fixing this later today

**Comment by Aebel-Shajan** [comment]
> > Also when using the --staged flag here:
> > ```
> > "lint:staged": "biome check --error-on-warnings --no-errors-on-unmatched --staged ./**/*.{js,ts}",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Biome gets applied to all staged files, not the staged .js and .ts files. Really weird they would do it like that.
> 
> Hmmm I think I missed using lint-staged which should let us specify that. Hmm 🤔
> 
> I can try fixing this later today.
> 
> https://biomejs.dev/recipes/git-hooks/

No worries I just made some changes here now: 
https://github.com/jaas666/Wocket-Weague/pull/1

**Comment by jaas666** [comment]
> > > Also when using the --staged flag here:
> > > ```
> > > "lint:staged": "biome check --error-on-warnings --no-errors-on-unmatched --staged ./**/*.{js,ts}",
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Biome gets applied to all staged files, not the staged .js and .ts files. Really weird they would do it like that.
> > 
> > 
> > Hmmm I think I missed using lint-staged which should let us specify that. Hmm 🤔
> > I can try fixing this later today.
> > https://biomejs.dev/recipes/git-hooks/
> 
> No worries I just made some changes here now: [jaas666#1](https://github.com/jaas666/Wocket-Weague/pull/1)

Check the PR in your repo. should be good now

**Review by Aebel-Shajan — APPROVED** [review]

**Comment by Aebel-Shajan** [comment]
Nice one !  Thanks for the pr

**Pull request merged**
